### ISSUE TITLE
yarn add doesn't work

### ISSUE THREAD

**Issue by 0scrm** [MacFJA/svelte-adapter-multi#2]
### Subject of the issue
The command `yarn add @macfja/svelte-adapter-multi` doesn't work.

### Your environment
* Yarn version: 1.22.17
* Node version: v17.2.0

### Steps to reproduce
Run `yarn add @macfja/svelte-adapter-multi`

### Expected behaviour
This should add the svelte-adapter-multi to the package json dependencies and download it to node_modules

### Actual behaviour
`An unexpected error occurred: "https://registry.yarnpkg.com/@macfja%2fsvelte-adapter-multi: Not found"`

**Comment by MacFJA** [comment]
I just try with :
 - Yarn `1.22.10` and Node `v14.16.1`
 - Yarn `1.22.17` and Node `v16.13.1`

And not issue at all 🤔

**Comment by MacFJA** [comment]
You have a "typo" in the package name.

The right name is `@macfja/svelte-multi-adapter` (and not `@macfja/svelte-adapter-multi`)
(The repository name is not the same as the package name, my bad)

**Comment by 0scrm** [comment]
Indeed, #3 has been created to mention that

**Comment by MacFJA** [comment]
Fixed in 2a4f7c2
